version: '3.7'

# Docker Compose configuration for Energy Trading Network
# This creates the blockchain network infrastructure for the industrial zone

networks:
  energy_network:
    name: energy_trading_network

services:
  # Orderer Service - Manages transaction ordering for the network
  orderer.energyzone.com:
    container_name: orderer.energyzone.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
    working_dir: /root
    command: orderer
    volumes:
      - ./organizations/ordererOrganizations/energyzone.com/orderers/orderer.energyzone.com/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/energyzone.com/orderers/orderer.energyzone.com/tls:/var/hyperledger/orderer/tls
      - orderer.energyzone.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
    networks:
      - energy_network

  # Peer0 for Industrial Organization - Represents factories in the zone
  peer0.industrial.energyzone.com:
    container_name: peer0.industrial.energyzone.com
    image: hyperledger/fabric-peer:latest
    environment:
      # Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.industrial.energyzone.com
      - CORE_PEER_ADDRESS=peer0.industrial.energyzone.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.industrial.energyzone.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.industrial.energyzone.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.industrial.energyzone.com:7051
      - CORE_PEER_LOCALMSPID=IndustrialMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      # CouchDB Configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - ./organizations/peerOrganizations/industrial.energyzone.com/peers/peer0.industrial.energyzone.com:/etc/hyperledger/fabric
      - peer0.industrial.energyzone.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
    depends_on:
      - couchdb
    networks:
      - energy_network

  # CouchDB - Database for storing blockchain state data
  couchdb:
    container_name: couchdb
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - energy_network

  # CLI - Command Line Interface for interacting with the network
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.industrial.energyzone.com:7051
      - CORE_PEER_LOCALMSPID=IndustrialMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/industrial.energyzone.com/peers/peer0.industrial.energyzone.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/industrial.energyzone.com/peers/peer0.industrial.energyzone.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/industrial.energyzone.com/peers/peer0.industrial.energyzone.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/industrial.energyzone.com/users/Admin@industrial.energyzone.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.industrial.energyzone.com
    networks:
      - energy_network

volumes:
  orderer.energyzone.com:
  peer0.industrial.energyzone.com:
